# Generated by Django 5.2.13 on 2026-04-09 23:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(blank=True, help_text='e.g. GJ-2024-HC-00001 — set by Registrar on registration', max_length=30, null=True, unique=True)),
                ('title', models.CharField(help_text='e.g. Ndure v. Ceesay', max_length=300)),
                ('court', models.CharField(choices=[('cadi', 'Cadi Court'), ('magistrate', 'Magistrates Court'), ('high', 'High Court'), ('appeal', 'Court of Appeal'), ('supreme', 'Supreme Court')], max_length=20)),
                ('case_type', models.CharField(choices=[('criminal_complaint', 'Criminal Complaint'), ('bail_application', 'Bail Application'), ('civil_claim', 'Civil Claim'), ('debt_recovery', 'Debt Recovery'), ('divorce', 'Divorce'), ('custody', 'Child Custody'), ('land_dispute', 'Land Dispute'), ('constitutional', 'Constitutional Matter'), ('islamic_family', 'Islamic Family Matter'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_accounts', 'Pending Accounts Review'), ('pending_registrar', 'Pending Registrar Review'), ('registered', 'Registered'), ('rejected', 'Rejected'), ('resubmitted', 'Resubmitted'), ('assigned', 'Assigned to Judge'), ('hearing_scheduled', 'Hearing Scheduled'), ('active', 'Active / In Hearing'), ('judgment_pending', 'Judgment Pending'), ('judgment_delivered', 'Judgment Delivered'), ('appeal_filed', 'Appeal Filed'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('description', models.TextField(blank=True, help_text='Brief facts of the case')),
                ('opposing_party_name', models.CharField(blank=True, max_length=200)),
                ('relief_sought', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When moved to PENDING_ACCOUNTS', null=True)),
                ('registered_at', models.DateTimeField(blank=True, help_text='When officially registered', null=True)),
                ('is_sealed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'case_forms',
            },
        ),
        migrations.CreateModel(
            name='CourtForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('court', models.CharField(choices=[('cadi', 'Cadi Court'), ('magistrate', 'Magistrates Court'), ('high', 'High Court'), ('appeal', 'Court of Appeal'), ('supreme', 'Supreme Court')], max_length=20)),
                ('case_type', models.CharField(blank=True, choices=[('criminal_complaint', 'Criminal Complaint'), ('bail_application', 'Bail Application'), ('civil_claim', 'Civil Claim'), ('debt_recovery', 'Debt Recovery'), ('divorce', 'Divorce'), ('custody', 'Child Custody'), ('land_dispute', 'Land Dispute'), ('constitutional', 'Constitutional Matter'), ('islamic_family', 'Islamic Family Matter'), ('other', 'Other')], max_length=50)),
                ('name', models.CharField(help_text='e.g. Originating Summons — High Court', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('fee_amount', models.DecimalField(decimal_places=2, help_text='Fee in GMD', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'court_forms',
                'ordering': ['court', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('staff_role', models.CharField(choices=[('accounts', 'Accounts Department'), ('registrar', 'Registrar')], max_length=20)),
                ('note', models.TextField()),
                ('action', models.CharField(choices=[('forwarded', 'Forwarded to Registrar'), ('registered', 'Case Registered'), ('rejected', 'Case Rejected'), ('flagged', 'Flagged for Correction')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'submission_notes',
                'ordering': ['created_at'],
            },
        ),
    ]
