# Generated by Django 5.2.13 on 2026-04-09 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('firms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='firms.lawyer'),
        ),
        migrations.AddField(
            model_name='caseform',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_forms', to='cases.case'),
        ),
        migrations.AlterUniqueTogether(
            name='courtform',
            unique_together={('court', 'name')},
        ),
        migrations.AddField(
            model_name='caseform',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cases.courtform'),
        ),
    ]
