# Generated by Django 5.2.13 on 2026-04-09 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionnote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionnote',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_notes', to='cases.case'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status'], name='cases_status_e2ca9e_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['court'], name='cases_court_401cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['submitted_by'], name='cases_submitt_d3d248_idx'),
        ),
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['case_number'], name='cases_case_nu_25894f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='caseform',
            unique_together={('case', 'form')},
        ),
    ]
