# Generated by Django 5.2.13 on 2026-04-09 23:36

import apps.documents.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('pleading', 'Pleading / Statement of Claim'), ('affidavit', 'Affidavit'), ('exhibit', 'Exhibit'), ('supporting', 'Supporting Document'), ('court_order', 'Court Order'), ('judgment', 'Judgment'), ('correspondence', 'Correspondence'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('file', models.FileField(upload_to=apps.documents.models.case_document_path)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('sha256_hash', models.CharField(help_text='SHA-256 of file content at upload time', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Soft delete — never hard-delete documents')),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.case')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
