# Generated by Django 5.2.13 on 2026-04-09 23:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='GMD', max_digits=10)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending — awaiting payment'), ('initiated', 'Initiated — sent to MUSU'), ('confirmed', 'Confirmed — payment received'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('musu_reference', models.CharField(blank=True, help_text='Reference returned by MUSU on initiation', max_length=100, null=True, unique=True)),
                ('musu_transaction_id', models.CharField(blank=True, help_text='Final transaction ID in MUSU system', max_length=100, null=True)),
                ('payer_phone', models.CharField(blank=True, help_text='Mobile number used to pay', max_length=20)),
                ('is_waived', models.BooleanField(default=False)),
                ('waiver_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('musu_raw_payload', models.JSONField(blank=True, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='cases.case')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='payments.payment')),
            ],
            options={
                'db_table': 'payment_receipts',
            },
        ),
    ]
