# Generated by Django 5.2.13 on 2026-04-09 23:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('bar_number', models.CharField(help_text='Gambia Bar Association firm registration number', max_length=50, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'law_firms',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bar_number', models.CharField(help_text='Individual bar registration number', max_length=50, unique=True)),
                ('specialisation', models.CharField(blank=True, help_text='e.g. Commercial, Criminal, Family', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lawyers',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
