# Generated by Django 5.2.13 on 2026-04-09 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('firms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lawfirm',
            name='admin_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_firm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_firms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawyers', to='firms.lawfirm'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
